"""
Single source of truth for the company list.

Each entry: {"ats": str, "token": str, "name": str, "tier": str, "verified": bool, "notes": str}

- "ats":      "greenhouse" | "lever" | "personio" | "ashby"
- "token":    URL slug used in the ATS API
- "verified": True  = confirmed via live API hit
              False = best-guess token, may need adjustment
- "tier":     "ai-native" | "scaleup" | "enterprise" | "platform"

The public COMPANIES list is deduplicated by (ats, token) automatically.
New entries appended by discover.py or serper_discover.py land in _RAW and
are deduplicated on the next import — so accidental duplicates never break things.
"""
from __future__ import annotations

_RAW: list[dict] = [

    # ===== ASHBY =====
    {"ats": "ashby", "token": "airbyte",              "name": "Airbyte",             "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "alephalpha",           "name": "Aleph Alpha",         "tier": "ai-native", "verified": True,  "notes": "Heidelberg; German LLM company"},
    {"ats": "ashby", "token": "amboss",               "name": "AMBOSS",              "tier": "scaleup",   "verified": True,  "notes": "Berlin; medical education"},
    {"ats": "ashby", "token": "anthropic",            "name": "Anthropic",           "tier": "ai-native", "verified": False, "notes": "US-mostly; EU remote rare"},
    {"ats": "ashby", "token": "axel",                 "name": "Axel Springer",       "tier": "enterprise","verified": True,  "notes": "Berlin; media group"},
    {"ats": "ashby", "token": "babbel",               "name": "Babbel",              "tier": "scaleup",   "verified": True,  "notes": "Berlin; language learning"},
    {"ats": "ashby", "token": "billie",               "name": "Billie",              "tier": "scaleup",   "verified": True,  "notes": "Berlin; B2B payments"},
    {"ats": "ashby", "token": "cohere",               "name": "Cohere",              "tier": "ai-native", "verified": True,  "notes": "Toronto/remote; EMEA roles"},
    {"ats": "ashby", "token": "contextual",           "name": "Contextual",          "tier": "ai-native", "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "cosuno",               "name": "Cosuno",              "tier": "scaleup",   "verified": True,  "notes": "Berlin; construction tech"},
    {"ats": "ashby", "token": "deepl",                "name": "DeepL",               "tier": "ai-native", "verified": True,  "notes": "Cologne, hybrid; Language AI"},
    {"ats": "ashby", "token": "elastic",              "name": "Elastic",             "tier": "platform",  "verified": True,  "notes": "Remote-first"},
    {"ats": "ashby", "token": "enpal",                "name": "Enpal",               "tier": "scaleup",   "verified": True,  "notes": "Berlin; solar"},
    {"ats": "ashby", "token": "flink",                "name": "Flink",               "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "ashby", "token": "forto",                "name": "Forto",               "tier": "scaleup",   "verified": True,  "notes": "Berlin; logistics"},
    {"ats": "ashby", "token": "fullstory",            "name": "Fullstory",           "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "hipeople-official",    "name": "HiPeople",            "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "infinity-constellation", "name": "Infinity Constellation", "tier": "scaleup", "verified": True, "notes": "serper+api verified"},
    {"ats": "ashby", "token": "jupus",                "name": "Jupus",               "tier": "ai-native", "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "langchain",            "name": "LangChain",           "tier": "ai-native", "verified": True,  "notes": "Remote-first"},
    {"ats": "ashby", "token": "linear",               "name": "Linear",              "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "llamaindex",           "name": "LlamaIndex",          "tier": "ai-native", "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "loom",                 "name": "Loom",                "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "mightybot",            "name": "Mightybot",           "tier": "ai-native", "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "mistral",              "name": "Mistral AI",          "tier": "ai-native", "verified": True,  "notes": "Paris; EU remote"},
    {"ats": "ashby", "token": "moss",                 "name": "Moss",                "tier": "scaleup",   "verified": True,  "notes": "Berlin; spend management"},
    {"ats": "ashby", "token": "n8n",                  "name": "n8n",                 "tier": "platform",  "verified": True,  "notes": "Berlin; workflow automation"},
    {"ats": "ashby", "token": "nelly",                "name": "Nelly",               "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "neon",                 "name": "Neon",                "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "nessolabs",            "name": "Nessolabs",           "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "notion",               "name": "Notion",              "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "pinecone",             "name": "Pinecone",            "tier": "ai-native", "verified": False, "notes": "US-mostly"},
    {"ats": "ashby", "token": "pliant",               "name": "Pliant",              "tier": "scaleup",   "verified": True,  "notes": "Berlin; corporate cards"},
    {"ats": "ashby", "token": "procurify",            "name": "Procurify",           "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "reedsy",               "name": "Reedsy",              "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "retool",               "name": "Retool",              "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "robco",                "name": "Robco",               "tier": "scaleup",   "verified": True,  "notes": "Munich; robotics"},
    {"ats": "ashby", "token": "rula",                 "name": "Rula",                "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "sentry",               "name": "Sentry",              "tier": "platform",  "verified": True,  "notes": "Remote EMEA"},
    {"ats": "ashby", "token": "skalar",               "name": "Skalar",              "tier": "ai-native", "verified": True,  "notes": "Munich; AI automation"},
    {"ats": "ashby", "token": "snowflake",            "name": "Snowflake",           "tier": "platform",  "verified": True,  "notes": "EMEA roles"},
    {"ats": "ashby", "token": "sprig",                "name": "Sprig",               "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "statista",             "name": "Statista",            "tier": "enterprise","verified": True,  "notes": "Hamburg; data platform"},
    {"ats": "ashby", "token": "supabase",             "name": "Supabase",            "tier": "platform",  "verified": True,  "notes": "Fully remote"},
    {"ats": "ashby", "token": "sylvera",              "name": "Sylvera",             "tier": "scaleup",   "verified": True,  "notes": "auto-discovered"},
    {"ats": "ashby", "token": "trm-labs",             "name": "TRM Labs",            "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "ashby", "token": "vercel",               "name": "Vercel",              "tier": "platform",  "verified": True,  "notes": "Remote-first"},
    {"ats": "ashby", "token": "voyfai",               "name": "Voyfai",              "tier": "ai-native", "verified": True,  "notes": "Berlin; serper+api verified"},
    {"ats": "ashby", "token": "weaviate",             "name": "Weaviate",            "tier": "ai-native", "verified": True,  "notes": "Amsterdam/remote EU"},

    # ===== GREENHOUSE =====
    {"ats": "greenhouse", "token": "11",                    "name": "1&1",                   "tier": "enterprise","verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "adahealth",             "name": "Ada Health",            "tier": "scaleup",   "verified": True,  "notes": "Berlin; AI medical"},
    {"ats": "greenhouse", "token": "algolia",               "name": "Algolia",               "tier": "platform",  "verified": True,  "notes": "Paris + remote"},
    {"ats": "greenhouse", "token": "amplitude",             "name": "Amplitude",             "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "anydesk",               "name": "AnyDesk",               "tier": "scaleup",   "verified": True,  "notes": "Stuttgart-based"},
    {"ats": "greenhouse", "token": "autoscout24",           "name": "AutoScout24",           "tier": "scaleup",   "verified": True,  "notes": "Berlin + Munich"},
    {"ats": "greenhouse", "token": "avimedical",            "name": "Avi Medical",           "tier": "scaleup",   "verified": True,  "notes": "Munich; digital GP"},
    {"ats": "greenhouse", "token": "blacklane",             "name": "Blacklane",             "tier": "scaleup",   "verified": True,  "notes": "Berlin; mobility"},
    {"ats": "greenhouse", "token": "bluefishai",            "name": "Bluefish AI",           "tier": "ai-native", "verified": True,  "notes": "Berlin/remote DE"},
    {"ats": "greenhouse", "token": "brainloop",             "name": "Brainloop",             "tier": "scaleup",   "verified": True,  "notes": "Munich; document security"},
    {"ats": "greenhouse", "token": "celonis",               "name": "Celonis",               "tier": "scaleup",   "verified": True,  "notes": "Munich HQ — top match"},
    {"ats": "greenhouse", "token": "circleci",              "name": "CircleCI",              "tier": "platform",  "verified": False, "notes": "Remote"},
    {"ats": "greenhouse", "token": "clarityai",             "name": "Clarity AI",            "tier": "ai-native", "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "commercetools",         "name": "Commercetools",         "tier": "scaleup",   "verified": True,  "notes": "Munich; commerce platform"},
    {"ats": "greenhouse", "token": "contentful",            "name": "Contentful",            "tier": "platform",  "verified": True,  "notes": "Berlin"},
    {"ats": "greenhouse", "token": "cresta",                "name": "Cresta",                "tier": "ai-native", "verified": True,  "notes": "Berlin; contact center AI"},
    {"ats": "greenhouse", "token": "cultureamp",            "name": "Culture Amp",           "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "databricks",            "name": "Databricks",            "tier": "platform",  "verified": True,  "notes": "Munich/Berlin office"},
    {"ats": "greenhouse", "token": "datadog",               "name": "Datadog",               "tier": "platform",  "verified": True,  "notes": "Paris/remote EMEA"},
    {"ats": "greenhouse", "token": "dataiku",               "name": "Dataiku",               "tier": "ai-native", "verified": True,  "notes": "Paris/Berlin/remote DE"},
    {"ats": "greenhouse", "token": "deepmind",              "name": "Google DeepMind",       "tier": "ai-native", "verified": True,  "notes": "London/remote; EMEA roles"},
    {"ats": "greenhouse", "token": "delivery-hero",         "name": "Delivery Hero",         "tier": "enterprise","verified": False, "notes": "Berlin; try 'deliveryhero' if 404"},
    {"ats": "greenhouse", "token": "diligentcorporation",   "name": "Diligent Corporation",  "tier": "enterprise","verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "doctolib",              "name": "Doctolib",              "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "greenhouse", "token": "elastic",               "name": "Elastic",               "tier": "platform",  "verified": True,  "notes": "Remote-first"},
    {"ats": "greenhouse", "token": "figma",                 "name": "Figma",                 "tier": "platform",  "verified": True,  "notes": "Berlin hub"},
    {"ats": "greenhouse", "token": "finanzcheck",           "name": "Finanzcheck",           "tier": "scaleup",   "verified": True,  "notes": "Hamburg"},
    {"ats": "greenhouse", "token": "fireworksai",           "name": "Fireworks AI",          "tier": "ai-native", "verified": True,  "notes": "US-heavy but remote possible"},
    {"ats": "greenhouse", "token": "flix",                  "name": "Flix",                  "tier": "scaleup",   "verified": True,  "notes": "Munich; mobility"},
    {"ats": "greenhouse", "token": "flink",                 "name": "Flink",                 "tier": "scaleup",   "verified": False, "notes": "Berlin"},
    {"ats": "greenhouse", "token": "fortifyiq",             "name": "FortifyIQ",             "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "future",                "name": "Future Processing",     "tier": "scaleup",   "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "getyourguide",          "name": "GetYourGuide",          "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "greenhouse", "token": "gitpod",                "name": "Gitpod",                "tier": "platform",  "verified": False, "notes": "Remote EU"},
    {"ats": "greenhouse", "token": "gitlab",                "name": "GitLab",                "tier": "platform",  "verified": True,  "notes": "Fully remote; AI Engineering"},
    {"ats": "greenhouse", "token": "grafanalabs",           "name": "Grafana Labs",          "tier": "platform",  "verified": True,  "notes": "Remote-first"},
    {"ats": "greenhouse", "token": "grammarly",             "name": "Grammarly",             "tier": "ai-native", "verified": True,  "notes": "Berlin hub being built"},
    {"ats": "greenhouse", "token": "hellofresh",            "name": "HelloFresh",            "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "greenhouse", "token": "helsing",               "name": "Helsing",               "tier": "scaleup",   "verified": True,  "notes": "Munich; defense AI — filtered by EXCLUDE_DEFENSE"},
    {"ats": "greenhouse", "token": "hextechnologies",       "name": "Hex Technologies",      "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "heycar",                "name": "Heycar",                "tier": "scaleup",   "verified": True,  "notes": "Berlin; car marketplace"},
    {"ats": "greenhouse", "token": "huggingface",           "name": "Hugging Face",          "tier": "ai-native", "verified": False, "notes": "Remote-first"},
    {"ats": "greenhouse", "token": "intercom",              "name": "Intercom",              "tier": "scaleup",   "verified": True,  "notes": "Berlin; AI-heavy (Fin)"},
    {"ats": "greenhouse", "token": "ionos",                 "name": "IONOS",                 "tier": "enterprise","verified": True,  "notes": "Montabaur; cloud hosting"},
    {"ats": "greenhouse", "token": "isaraerospace",         "name": "Isar Aerospace",        "tier": "scaleup",   "verified": True,  "notes": "Munich; rocketry"},
    {"ats": "greenhouse", "token": "jetbrains",             "name": "JetBrains",             "tier": "platform",  "verified": True,  "notes": "Munich/Berlin; eu.greenhouse.io"},
    {"ats": "greenhouse", "token": "klaviyo",               "name": "Klaviyo",               "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "langchain",             "name": "LangChain",             "tier": "ai-native", "verified": False, "notes": "Remote-first"},
    {"ats": "greenhouse", "token": "miro",                  "name": "Miro",                  "tier": "scaleup",   "verified": False, "notes": "Berlin + remote EU"},
    {"ats": "greenhouse", "token": "mirakllabs",            "name": "Mirakl Labs",           "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "mixpanel",              "name": "Mixpanel",              "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "mongodb",               "name": "MongoDB",               "tier": "platform",  "verified": True,  "notes": "Germany office + remote"},
    {"ats": "greenhouse", "token": "n26",                   "name": "N26",                   "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "greenhouse", "token": "navvis",                "name": "NavVis",                "tier": "scaleup",   "verified": True,  "notes": "Munich; spatial intelligence"},
    {"ats": "greenhouse", "token": "nscaleoperationsukltd", "name": "Nscale",                "tier": "ai-native", "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "openai",                "name": "OpenAI",                "tier": "ai-native", "verified": False, "notes": "US-heavy"},
    {"ats": "greenhouse", "token": "optimaldynamics",       "name": "Optimal Dynamics",      "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "pandadoc",              "name": "PandaDoc",              "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "parloa",                "name": "Parloa",                "tier": "ai-native", "verified": True,  "notes": "Berlin; conversational AI"},
    {"ats": "greenhouse", "token": "personio",              "name": "Personio",              "tier": "scaleup",   "verified": False, "notes": "Munich; building AI features"},
    {"ats": "greenhouse", "token": "picsart",               "name": "Picsart",               "tier": "scaleup",   "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "planetscale",           "name": "PlanetScale",           "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "qdrant",                "name": "Qdrant",                "tier": "ai-native", "verified": False, "notes": "Berlin-based!"},
    {"ats": "greenhouse", "token": "raisin",                "name": "Raisin",                "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "greenhouse", "token": "remotepeople",          "name": "Remote People",         "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "replicate",             "name": "Replicate",             "tier": "ai-native", "verified": False, "notes": "Remote"},
    {"ats": "greenhouse", "token": "robotsandpencils",      "name": "Robots and Pencils",    "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "scaleai",               "name": "Scale AI",              "tier": "ai-native", "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "scout24",               "name": "Scout24",               "tier": "scaleup",   "verified": True,  "notes": "Munich; real estate"},
    {"ats": "greenhouse", "token": "snowflake",             "name": "Snowflake",             "tier": "platform",  "verified": False, "notes": "EMEA roles"},
    {"ats": "greenhouse", "token": "solarisbank",           "name": "Solarisbank",           "tier": "scaleup",   "verified": True,  "notes": "Berlin; BaaS"},
    {"ats": "greenhouse", "token": "sonatus",               "name": "Sonatus",               "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "splitero",              "name": "Splitero",              "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "greenhouse", "token": "stabilityai",           "name": "Stability AI",          "tier": "ai-native", "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "staffbase",             "name": "Staffbase",             "tier": "scaleup",   "verified": True,  "notes": "Chemnitz/Berlin/remote"},
    {"ats": "greenhouse", "token": "strato",                "name": "Strato",                "tier": "enterprise","verified": True,  "notes": "Berlin; web hosting"},
    {"ats": "greenhouse", "token": "sts",                   "name": "STS Software",          "tier": "scaleup",   "verified": True,  "notes": "auto-discovered"},
    {"ats": "greenhouse", "token": "sumup",                 "name": "SumUp",                 "tier": "scaleup",   "verified": True,  "notes": "Berlin; payments"},
    {"ats": "greenhouse", "token": "traderepublic",         "name": "Trade Republic",        "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "greenhouse", "token": "vercel",                "name": "Vercel",                "tier": "platform",  "verified": True,  "notes": "Remote-first"},
    {"ats": "greenhouse", "token": "wefox",                 "name": "wefox",                 "tier": "scaleup",   "verified": False, "notes": "Berlin"},
    {"ats": "greenhouse", "token": "zalando",               "name": "Zalando",               "tier": "scaleup",   "verified": False, "notes": "Berlin/Dublin"},

    # ===== LEVER =====
    {"ats": "lever", "token": "aleph",                  "name": "Aleph Alpha",           "tier": "ai-native", "verified": True,  "notes": "Heidelberg"},
    {"ats": "lever", "token": "alephalpha",             "name": "Aleph Alpha",           "tier": "ai-native", "verified": False, "notes": "alternative token; try 'aleph' if 404"},
    {"ats": "lever", "token": "atmosera",               "name": "Atmosera",              "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "binance",                "name": "Binance",               "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "contentsquare",          "name": "Contentsquare",         "tier": "scaleup",   "verified": True,  "notes": "Paris/remote EU"},
    {"ats": "lever", "token": "egen",                   "name": "Egen",                  "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "eleks",                  "name": "ELEKS",                 "tier": "scaleup",   "verified": True,  "notes": "auto-discovered"},
    {"ats": "lever", "token": "hsag",                   "name": "HSAG",                  "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "instrument",             "name": "Instrument",            "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "jetbrains",              "name": "JetBrains",             "tier": "platform",  "verified": True,  "notes": "Munich/Berlin"},
    {"ats": "lever", "token": "lingarogroup",           "name": "Lingaro Group",         "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "mistral",                "name": "Mistral AI",            "tier": "ai-native", "verified": True,  "notes": "Paris; EU remote"},
    {"ats": "lever", "token": "neon",                   "name": "Neon",                  "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "lever", "token": "octopus",                "name": "Octopus Energy Germany","tier": "scaleup",   "verified": True,  "notes": "Berlin; energy"},
    {"ats": "lever", "token": "palantir",               "name": "Palantir Germany",      "tier": "enterprise","verified": True,  "notes": "Munich office"},
    {"ats": "lever", "token": "panopto",                "name": "Panopto",               "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "saga-xyz",               "name": "Saga",                  "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "sonarsource",            "name": "SonarSource",           "tier": "platform",  "verified": True,  "notes": "Geneva/remote EU"},
    {"ats": "lever", "token": "supabase",               "name": "Supabase",              "tier": "platform",  "verified": False, "notes": "Fully remote"},
    {"ats": "lever", "token": "tryjeeves",              "name": "Tryjeeves",             "tier": "ai-native", "verified": True,  "notes": "serper+api verified"},
    {"ats": "lever", "token": "unstructuredtechnologies", "name": "Unstructured Technologies", "tier": "ai-native", "verified": True, "notes": "serper+api verified"},

    # ===== PERSONIO =====
    {"ats": "personio", "token": "1komma5grad",         "name": "1KOMMA5°",              "tier": "scaleup",   "verified": False, "notes": "Hamburg; energy transition"},
    {"ats": "personio", "token": "aboutyou",            "name": "About You",             "tier": "scaleup",   "verified": True,  "notes": "Hamburg; fashion"},
    {"ats": "personio", "token": "ada",                 "name": "Ada Health",            "tier": "scaleup",   "verified": True,  "notes": "Berlin; medical AI"},
    {"ats": "personio", "token": "agile-robots-se",     "name": "Agile Robots SE",       "tier": "scaleup",   "verified": True,  "notes": "Munich; robotics"},
    {"ats": "personio", "token": "alphapet-ventures",   "name": "AlphaPet Ventures",     "tier": "scaleup",   "verified": True,  "notes": "Munich; pet food"},
    {"ats": "personio", "token": "amazon",              "name": "Amazon Germany",        "tier": "enterprise","verified": True,  "notes": "auto-discovered"},
    {"ats": "personio", "token": "amboss",              "name": "AMBOSS",                "tier": "scaleup",   "verified": False, "notes": "Berlin; medical education"},
    {"ats": "personio", "token": "appliedai",           "name": "appliedAI",             "tier": "ai-native", "verified": True,  "notes": "Munich; AI institute"},
    {"ats": "personio", "token": "appsfactory-gmbh",   "name": "appsfactory GmbH",      "tier": "scaleup",   "verified": True,  "notes": "Leipzig; serper+api verified"},
    {"ats": "personio", "token": "avimedical",          "name": "Avi Medical",           "tier": "scaleup",   "verified": True,  "notes": "Munich; digital GP"},
    {"ats": "personio", "token": "carbmee",             "name": "Carbmee",               "tier": "scaleup",   "verified": True,  "notes": "Berlin; carbon management"},
    {"ats": "personio", "token": "celonis",             "name": "Celonis",               "tier": "scaleup",   "verified": True,  "notes": "Munich HQ"},
    {"ats": "personio", "token": "certivity",           "name": "Certivity",             "tier": "scaleup",   "verified": True,  "notes": "Munich; serper+api verified"},
    {"ats": "personio", "token": "check24",             "name": "Check24",               "tier": "scaleup",   "verified": True,  "notes": "Munich"},
    {"ats": "personio", "token": "circula",             "name": "Circula",               "tier": "scaleup",   "verified": True,  "notes": "Berlin; expense management"},
    {"ats": "personio", "token": "clark",               "name": "Clark",                 "tier": "scaleup",   "verified": True,  "notes": "Frankfurt; insurance"},
    {"ats": "personio", "token": "clue",                "name": "Clue",                  "tier": "scaleup",   "verified": False, "notes": "Berlin; femtech"},
    {"ats": "personio", "token": "cosuno",              "name": "Cosuno",                "tier": "scaleup",   "verified": True,  "notes": "Berlin; construction"},
    {"ats": "personio", "token": "doctolib",            "name": "Doctolib",              "tier": "scaleup",   "verified": False, "notes": "Berlin"},
    {"ats": "personio", "token": "enpal",               "name": "Enpal",                 "tier": "scaleup",   "verified": False, "notes": "Berlin; solar"},
    {"ats": "personio", "token": "esentri",             "name": "Esentri",               "tier": "scaleup",   "verified": True,  "notes": "Ettlingen; serper+api verified"},
    {"ats": "personio", "token": "factorial",           "name": "Factorial HR",          "tier": "scaleup",   "verified": True,  "notes": "Barcelona/remote"},
    {"ats": "personio", "token": "gaia-group",          "name": "GAIA",                  "tier": "scaleup",   "verified": False, "notes": "Hamburg; digital therapeutics"},
    {"ats": "personio", "token": "hetzner",             "name": "Hetzner",               "tier": "enterprise","verified": True,  "notes": "Nuremberg; cloud hosting"},
    {"ats": "personio", "token": "hpe",                 "name": "HPE Germany",           "tier": "enterprise","verified": True,  "notes": "auto-discovered"},
    {"ats": "personio", "token": "imap-gmbh-1",         "name": "imap GmbH",             "tier": "scaleup",   "verified": True,  "notes": "Düsseldorf; serper+api verified"},
    {"ats": "personio", "token": "integrity-next-gmbh", "name": "Integrity Next GmbH",  "tier": "scaleup",   "verified": True,  "notes": "serper+api verified"},
    {"ats": "personio", "token": "jtl-software-gmbh",  "name": "JTL Software GmbH",     "tier": "scaleup",   "verified": True,  "notes": "Wuppertal; serper+api verified"},
    {"ats": "personio", "token": "linear",              "name": "Linear",                "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "personio", "token": "moss",                "name": "Moss",                  "tier": "scaleup",   "verified": True,  "notes": "Berlin; spend management"},
    {"ats": "personio", "token": "navvis",              "name": "NavVis",                "tier": "scaleup",   "verified": True,  "notes": "Munich"},
    {"ats": "personio", "token": "neon",                "name": "Neon",                  "tier": "platform",  "verified": True,  "notes": "auto-discovered"},
    {"ats": "personio", "token": "nfon",                "name": "NFON",                  "tier": "scaleup",   "verified": True,  "notes": "Munich; cloud telephony"},
    {"ats": "personio", "token": "ommax",               "name": "OMMAX",                 "tier": "scaleup",   "verified": True,  "notes": "Munich; digital strategy"},
    {"ats": "personio", "token": "ottonova",            "name": "Ottonova",              "tier": "scaleup",   "verified": True,  "notes": "Munich; digital health insurance"},
    {"ats": "personio", "token": "penta",               "name": "Penta",                 "tier": "scaleup",   "verified": True,  "notes": "Berlin; business banking"},
    {"ats": "personio", "token": "personio",            "name": "Personio",              "tier": "scaleup",   "verified": True,  "notes": "Munich; HR software"},
    {"ats": "personio", "token": "pitch",               "name": "Pitch",                 "tier": "scaleup",   "verified": True,  "notes": "Berlin; presentation tool"},
    {"ats": "personio", "token": "solarisbank",         "name": "Solaris",               "tier": "scaleup",   "verified": False, "notes": "Berlin; BaaS"},
    {"ats": "personio", "token": "sonomotors",          "name": "Sono Motors",           "tier": "scaleup",   "verified": True,  "notes": "Munich; solar mobility"},
    {"ats": "personio", "token": "spiegel-gruppe",      "name": "Der Spiegel",           "tier": "enterprise","verified": False, "notes": "Hamburg; news media"},
    {"ats": "personio", "token": "statworx",            "name": "statworx",              "tier": "scaleup",   "verified": True,  "notes": "Frankfurt; AI consulting"},
    {"ats": "personio", "token": "tado",                "name": "tado°",                 "tier": "scaleup",   "verified": True,  "notes": "Munich; smart heating"},
    {"ats": "personio", "token": "tier",                "name": "TIER",                  "tier": "scaleup",   "verified": False, "notes": "Berlin; e-mobility"},
    {"ats": "personio", "token": "traderepublic",       "name": "Trade Republic",        "tier": "scaleup",   "verified": True,  "notes": "Berlin"},
    {"ats": "personio", "token": "userlane",            "name": "Userlane",              "tier": "scaleup",   "verified": True,  "notes": "Munich; digital adoption"},
    {"ats": "personio", "token": "verivox",             "name": "Verivox",               "tier": "enterprise","verified": True,  "notes": "Heidelberg; comparison portal"},
    {"ats": "personio", "token": "wundermobility",      "name": "Wunder Mobility",       "tier": "scaleup",   "verified": True,  "notes": "Hamburg"},
    {"ats": "personio", "token": "xitaso",              "name": "Xitaso",                "tier": "scaleup",   "verified": True,  "notes": "Augsburg; serper+api verified"},
    {"ats": "personio", "token": "xolife",              "name": "XO Life GmbH",          "tier": "scaleup",   "verified": True,  "notes": "Berlin; serper+api verified"},
    {"ats": "personio", "token": "zeit-online",         "name": "Die Zeit",              "tier": "enterprise","verified": False, "notes": "Hamburg; news media"},

    {"ats": "ashby", "token": "phoenix", "name": "Phoenix Contact", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 8 open jobs"},
    {"ats": "greenhouse", "token": "jungheinrich", "name": "Jungheinrich", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 17 open jobs"},
    {"ats": "greenhouse", "token": "phoenixcontact", "name": "Phoenix Contact", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 35 open jobs"},
    {"ats": "greenhouse", "token": "sixt", "name": "Sixt", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "carl", "name": "Carl Zeiss", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "hermes", "name": "Hermes Germany", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "phoenix", "name": "Phoenix Contact", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 13 open jobs"},
    {"ats": "personio", "token": "webasto", "name": "Webasto", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    # --- Serper-discovered (name corrected, broken entries removed) ---
    {"ats": "ashby", "token": "fieldguide",       "name": "Fieldguide",           "tier": "scaleup",   "verified": True,  "notes": "AI audit platform; remote US/EU"},
    {"ats": "ashby", "token": "zapier",           "name": "Zapier",               "tier": "platform",  "verified": True,  "notes": "workflow automation; remote"},
    {"ats": "ashby", "token": "percepta",         "name": "Percepta",             "tier": "ai-native", "verified": True,  "notes": "AI platform; Europe remote"},
    {"ats": "ashby", "token": "amigo",            "name": "Amigo",                "tier": "ai-native", "verified": True,  "notes": "AI; Europe remote"},
    {"ats": "ashby", "token": "hyperexponential", "name": "Hyperexponential",     "tier": "scaleup",   "verified": True,  "notes": "insurance AI; London/remote"},
    {"ats": "greenhouse", "token": "figure",          "name": "Figure",               "tier": "scaleup",   "verified": True,  "notes": "humanoid robotics; remote"},
    {"ats": "greenhouse", "token": "humansignal",     "name": "HumanSignal",          "tier": "ai-native", "verified": True,  "notes": "Label Studio; remote EU"},
    {"ats": "greenhouse", "token": "leolabsinc",      "name": "Leo Labs",             "tier": "scaleup",   "verified": True,  "notes": "space AI"},
    {"ats": "greenhouse", "token": "pairteam",        "name": "PairTeam",             "tier": "ai-native", "verified": True,  "notes": "AI customer success"},
    {"ats": "greenhouse", "token": "samsara",         "name": "Samsara",              "tier": "scaleup",   "verified": True,  "notes": "IoT/AI; EMEA roles"},
    {"ats": "greenhouse", "token": "securityscorecard","name": "SecurityScorecard",   "tier": "scaleup",   "verified": True,  "notes": "cybersecurity AI; remote"},
    {"ats": "greenhouse", "token": "stackblitz",      "name": "StackBlitz",          "tier": "platform",  "verified": True,  "notes": "AI dev tools; remote"},
    {"ats": "lever", "token": "imo-online",       "name": "imo",                  "tier": "scaleup",   "verified": True,  "notes": "messaging AI"},
    {"ats": "lever", "token": "conversica",       "name": "Conversica",           "tier": "ai-native", "verified": True,  "notes": "conversational AI; remote"},
    {"ats": "lever", "token": "weekdayworks",     "name": "Weekday",              "tier": "ai-native", "verified": True,  "notes": "AI recruiting platform"},
    {"ats": "personio", "token": "planb",         "name": "Plan B",               "tier": "scaleup",   "verified": True,  "notes": "Germany; GenAI/Data Science"},
    # --- Globale AI-native / Platform-Firmen mit EU-Remote (Ashby) ---
    {"ats": "ashby", "token": "wandb",            "name": "Weights & Biases",     "tier": "ai-native", "verified": True,  "notes": "MLOps platform; remote EU"},
    {"ats": "ashby", "token": "modal-labs",       "name": "Modal",                "tier": "ai-native", "verified": True,  "notes": "GPU cloud; remote"},
    {"ats": "ashby", "token": "dust",             "name": "Dust",                 "tier": "ai-native", "verified": True,  "notes": "Paris; AI workspace"},
    {"ats": "ashby", "token": "hightouch",        "name": "Hightouch",            "tier": "platform",  "verified": True,  "notes": "data activation; remote"},
    {"ats": "ashby", "token": "dbtlabs",          "name": "dbt Labs",             "tier": "platform",  "verified": True,  "notes": "data transformation; remote"},
    {"ats": "ashby", "token": "glean",            "name": "Glean",                "tier": "ai-native", "verified": True,  "notes": "enterprise AI search; EMEA"},
    {"ats": "ashby", "token": "kapa",             "name": "Kapa.ai",              "tier": "ai-native", "verified": True,  "notes": "Berlin; technical AI assistant"},
    {"ats": "ashby", "token": "typeform",         "name": "Typeform",             "tier": "platform",  "verified": True,  "notes": "Barcelona; forms + AI"},
    {"ats": "ashby", "token": "brex",             "name": "Brex",                 "tier": "scaleup",   "verified": True,  "notes": "fintech; remote EMEA"},
    {"ats": "ashby", "token": "together-ai",      "name": "Together AI",          "tier": "ai-native", "verified": False, "notes": "LLM inference; remote"},
    {"ats": "ashby", "token": "letta",            "name": "Letta (MemGPT)",       "tier": "ai-native", "verified": False, "notes": "agentic AI; remote"},
    # --- Globale AI-native / Platform-Firmen mit EU-Remote (Greenhouse) ---
    {"ats": "greenhouse", "token": "klarna",          "name": "Klarna",               "tier": "scaleup",   "verified": True,  "notes": "Stockholm/Berlin; heavy AI"},
    {"ats": "greenhouse", "token": "braze",           "name": "Braze",                "tier": "scaleup",   "verified": True,  "notes": "Berlin office; marketing AI"},
    {"ats": "greenhouse", "token": "zendesk",         "name": "Zendesk",              "tier": "enterprise","verified": True,  "notes": "Berlin; AI customer service"},
    {"ats": "greenhouse", "token": "thoughtworks",    "name": "ThoughtWorks",         "tier": "enterprise","verified": True,  "notes": "Stuttgart/Munich; consulting"},
    {"ats": "greenhouse", "token": "adjust",          "name": "Adjust",               "tier": "scaleup",   "verified": True,  "notes": "Berlin; mobile analytics"},
    {"ats": "greenhouse", "token": "mambu",           "name": "Mambu",                "tier": "scaleup",   "verified": True,  "notes": "Berlin; banking platform"},
    {"ats": "greenhouse", "token": "writer",          "name": "Writer",               "tier": "ai-native", "verified": False, "notes": "enterprise GenAI; remote EU"},
    {"ats": "greenhouse", "token": "descript",        "name": "Descript",             "tier": "ai-native", "verified": False, "notes": "AI media editing; remote"},
    {"ats": "greenhouse", "token": "bryter",          "name": "BRYTER",               "tier": "scaleup",   "verified": False, "notes": "Frankfurt; no-code automation"},
    {"ats": "greenhouse", "token": "idealo",          "name": "idealo",               "tier": "scaleup",   "verified": False, "notes": "Berlin; price comparison"},
    {"ats": "greenhouse", "token": "teamviewer",      "name": "TeamViewer",           "tier": "enterprise","verified": False, "notes": "Göppingen; remote software"},
    {"ats": "greenhouse", "token": "chronext",        "name": "Chronext",             "tier": "scaleup",   "verified": False, "notes": "Cologne; luxury watches"},
    {"ats": "greenhouse", "token": "tourlane",        "name": "Tourlane",             "tier": "scaleup",   "verified": False, "notes": "Berlin; AI travel planning"},
    {"ats": "greenhouse", "token": "attentive",       "name": "Attentive",            "tier": "scaleup",   "verified": False, "notes": "marketing AI; remote EU"},
    {"ats": "greenhouse", "token": "hubspot",         "name": "HubSpot",              "tier": "enterprise","verified": True,  "notes": "Berlin office; AI CRM"},
    {"ats": "greenhouse", "token": "dbt-labs",        "name": "dbt Labs",             "tier": "platform",  "verified": False, "notes": "alt token for dbtlabs"},
    # --- Deutsche Mittelstand / AI-Consulting (Personio) ---
    {"ats": "personio", "token": "inovex",        "name": "inovex GmbH",          "tier": "scaleup",   "verified": False, "notes": "Karlsruhe/Munich; AI engineering consulting"},
    {"ats": "personio", "token": "codecentric",   "name": "codecentric AG",       "tier": "scaleup",   "verified": False, "notes": "Solingen/Munich; ML/AI engineering"},
    {"ats": "personio", "token": "tng",           "name": "TNG Technology",       "tier": "scaleup",   "verified": False, "notes": "Munich/Unterföhring; AI consulting"},
    {"ats": "personio", "token": "object-code",   "name": "Object Code",          "tier": "scaleup",   "verified": False, "notes": "Germany; software + AI"},
    {"ats": "personio", "token": "merantix",      "name": "Merantix",             "tier": "ai-native", "verified": False, "notes": "Berlin; AI venture studio"},
    {"ats": "personio", "token": "ki-group",      "name": "KI Group",             "tier": "ai-native", "verified": False, "notes": "Germany; AI consulting"},
    {"ats": "personio", "token": "7lytic",        "name": "7lytic",               "tier": "ai-native", "verified": False, "notes": "Munich; AI analytics"},
    {"ats": "personio", "token": "mayflower",     "name": "Mayflower GmbH",       "tier": "scaleup",   "verified": False, "notes": "Munich; IT consulting + AI"},
    {"ats": "personio", "token": "andrena",       "name": "andrena objects AG",   "tier": "scaleup",   "verified": False, "notes": "Karlsruhe; software engineering"},
    # --- Lever Ergänzungen ---
    {"ats": "lever", "token": "sourcegraph",      "name": "Sourcegraph",          "tier": "platform",  "verified": True,  "notes": "AI code search; remote"},
    {"ats": "lever", "token": "replit",           "name": "Replit",               "tier": "platform",  "verified": True,  "notes": "AI dev environment; remote"},
    {"ats": "lever", "token": "huggingface",      "name": "Hugging Face",         "tier": "ai-native", "verified": True,  "notes": "Paris; EU remote"},
    {"ats": "lever", "token": "typeface",         "name": "Typeface",             "tier": "ai-native", "verified": False, "notes": "GenAI content platform; remote"},
    {"ats": "lever", "token": "vectara",          "name": "Vectara",              "tier": "ai-native", "verified": False, "notes": "RAG platform; remote EU"},
    {"ats": "ashby", "token": "happyhotel", "name": "happyhotel", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 26 open jobs"},
    {"ats": "ashby", "token": "hawk", "name": "Hawk", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 14 open jobs"},
    {"ats": "ashby", "token": "luminovo", "name": "Luminovo", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 11 open jobs"},
    {"ats": "ashby", "token": "manex", "name": "Manex AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 5 open jobs"},
    {"ats": "ashby", "token": "orbem", "name": "Orbem", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "ashby", "token": "quantum", "name": "Quantum Systems Limited", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 11 open jobs"},
    {"ats": "ashby", "token": "secfix", "name": "Secfix", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 9 open jobs"},
    {"ats": "ashby", "token": "tacto", "name": "tacto", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 25 open jobs"},
    {"ats": "greenhouse", "token": "arculus", "name": "Arculus", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 5 open jobs"},
    {"ats": "greenhouse", "token": "fernride", "name": "Fernride", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 11 open jobs"},
    {"ats": "greenhouse", "token": "idnow", "name": "IDnow", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 13 open jobs"},
    {"ats": "greenhouse", "token": "kinexon", "name": "KINEXON", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 21 open jobs"},
    {"ats": "greenhouse", "token": "konux", "name": "KONUX", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "36zerovision", "name": "36ZERO Vision", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "blickfeld", "name": "Blickfeld", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 2 open jobs"},
    {"ats": "personio", "token": "build38", "name": "Build38", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "building-radar", "name": "Building Radar", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 10 open jobs"},
    {"ats": "personio", "token": "celus", "name": "Celus", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "climedo", "name": "Climedo Health", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "cobrainer", "name": "Cobrainer", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 2 open jobs"},
    {"ats": "personio", "token": "deep", "name": "Deep North, Inc.", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "driveblocks", "name": "Driveblocks", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "ebenbuild", "name": "Ebenbuild", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "egym", "name": "Egym", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 59 open jobs"},
    {"ats": "personio", "token": "exomatter", "name": "ExoMatter", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "idnow", "name": "IDnow", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "konux", "name": "KONUX", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "magazino", "name": "Magazino", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 5 open jobs"},
    {"ats": "personio", "token": "manex-ai", "name": "Manex AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 4 open jobs"},
    {"ats": "personio", "token": "ororatech", "name": "OroraTech", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 2 open jobs"},
    {"ats": "personio", "token": "quantum", "name": "Quantum Systems Limited", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "rencore", "name": "Rencore", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 4 open jobs"},
    {"ats": "personio", "token": "retorio", "name": "retorio", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "sewts", "name": "Sewts", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 6 open jobs"},
    {"ats": "personio", "token": "smartreporting", "name": "Smart Reporting", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "studysmarter", "name": "StudySmarter", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "tacto", "name": "tacto", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "twaice", "name": "Twaice", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "twaice", "name": "Twaice", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "unitelabs", "name": "UniteLabs", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 2 open jobs"},
    {"ats": "ashby", "token": "finto", "name": "Finto.", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 8 open jobs"},
    {"ats": "ashby", "token": "mercura", "name": "Mercura AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 14 open jobs"},
    {"ats": "ashby", "token": "orbit", "name": "Orbit Health GmbH", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 2 open jobs"},
    {"ats": "greenhouse", "token": "alpineeagle", "name": "Alpine Eagle GmbH", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 16 open jobs"},
    {"ats": "lever", "token": "freeletics", "name": "Freeletics", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "freeletics", "name": "Freeletics", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "futurail", "name": "Futurail", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "lytra", "name": "lytra", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 4 open jobs"},
    {"ats": "personio", "token": "mpiriq", "name": "MPIRIQ", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "pactos", "name": "Pactos", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "pruna-ai", "name": "Pruna AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "temedica", "name": "Temedica GmbH", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 5 open jobs"},
    {"ats": "personio", "token": "vidlab7", "name": "VidLab7", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "ashby", "token": "mindpeak", "name": "MindPeak GmbH", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 13 open jobs"},
    {"ats": "personio", "token": "cargonexx", "name": "Cargonexx", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "circus", "name": "Circus Group", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 14 open jobs"},
    {"ats": "personio", "token": "collectai", "name": "collectAI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "hello", "name": "Hello Pine", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "insurfox", "name": "INSURFOX", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "oxolo", "name": "Oxolo", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "repath", "name": "repath", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "sonia", "name": "Sonia", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "ashby", "token": "deltia", "name": "Deltia", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 16 open jobs"},
    {"ats": "ashby", "token": "flankai", "name": "Flank AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 2 open jobs"},
    {"ats": "ashby", "token": "langdock", "name": "Langdock", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 7 open jobs"},
    {"ats": "ashby", "token": "peec", "name": "Peec AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 30 open jobs"},
    {"ats": "ashby", "token": "platoapp", "name": "Platoapp AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 7 open jobs"},
    {"ats": "ashby", "token": "prior-labs", "name": "Prior Labs", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 17 open jobs"},
    {"ats": "ashby", "token": "qontext", "name": "Qontext GmbH", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 6 open jobs"},
    {"ats": "ashby", "token": "synthflow", "name": "Synthflow AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 15 open jobs"},
    {"ats": "ashby", "token": "telli", "name": "telli (telli.com)", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 10 open jobs"},
    {"ats": "greenhouse", "token": "diligent", "name": "Diligent ( godiligent.ai )", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 8 open jobs"},
    {"ats": "lever", "token": "super", "name": "Super", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 14 open jobs"},
    {"ats": "personio", "token": "apheris", "name": "Apheris", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 5 open jobs"},
    {"ats": "personio", "token": "freshflow", "name": "FreshFlow", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "langdock", "name": "Langdock", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 3 open jobs"},
    {"ats": "personio", "token": "omnius", "name": "omni:us", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "peec-ai", "name": "Peec AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "platoapp", "name": "Platoapp AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "ashby", "token": "amber", "name": "Amber", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 14 open jobs"},
    {"ats": "ashby", "token": "maple", "name": "Maple Aviation", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 12 open jobs"},
    {"ats": "ashby", "token": "superduper", "name": "Superduper Agents", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 4 open jobs"},
    {"ats": "ashby", "token": "zeit-ai", "name": "Zeit AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 4 open jobs"},
    {"ats": "greenhouse", "token": "blackforestlabs", "name": "Black Forest Labs", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 13 open jobs"},
    {"ats": "greenhouse", "token": "unframe", "name": "unframe", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 54 open jobs"},
    {"ats": "personio", "token": "aedifion", "name": "aedifion GmbH", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 11 open jobs"},
    {"ats": "personio", "token": "amber", "name": "Amber", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "atmo", "name": "ATMO", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "personio", "token": "blockbrain", "name": "Blockbrain", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "compredict", "name": "COMPREDICT GmbH", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 4 open jobs"},
    {"ats": "personio", "token": "genow", "name": "Genow", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 1 open jobs"},
    {"ats": "personio", "token": "traide-ai", "name": "Traide AI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 6 open jobs"},
    {"ats": "personio", "token": "visionai", "name": "VisionAI", "tier": "scaleup", "verified": True, "notes": "auto-discovered, 0 open jobs"},
    {"ats": "ashby", "token": "Pulsora%20Inc", "name": "AI Engineer - United States @ Pulsora, Inc. -", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 6 open jobs"},
    {"ats": "ashby", "token": "concentrate%20ai", "name": "AI Engineer @ Concentrate AI -", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 2 open jobs"},
    {"ats": "ashby", "token": "pulsora%20inc", "name": "Applied AI Engineer - US @ Pulsora, Inc. -", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 6 open jobs"},
    {"ats": "greenhouse", "token": "pathward", "name": "Pathward", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 35 open jobs"},
    {"ats": "lever", "token": "jobgether", "name": "Jobgether", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 4847 open jobs"},
    {"ats": "lever", "token": "quantco-", "name": "Quantco ", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 18 open jobs"},
    {"ats": "lever", "token": "RyzLabs", "name": "Ryzlabs", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 49 open jobs"},
    {"ats": "lever", "token": "swordhealth", "name": "Swordhealth", "tier": "scaleup", "verified": True, "notes": "serper+api verified, 77 open jobs"},
    {"ats": "personio", "token": "exb", "name": "- Personio", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Hannover' OR 'Leipzig') AND '"},
    {"ats": "personio", "token": "gesundde", "name": "AI Engineer (m/w/d) - München oder Mobile Office |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('München' OR 'Bremen') AND 'Remote'"},
    {"ats": "personio", "token": "htgf", "name": "AI Engineer (m/w/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('München' OR 'Bremen') AND 'Remote'"},
    {"ats": "personio", "token": "turbalance", "name": "AI Trace Generation Engineer |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' AND ('Mannheim' OR 'Heidelberg') AND 'Remot"},
    {"ats": "personio", "token": "asellerate-gmbh", "name": "Asellerate Gmbh", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' AND ('Düsseldorf' OR 'Stuttgart') AND 'Remo"},
    {"ats": "personio", "token": "beroe-inc", "name": "Beroe x nnamu ...", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "bots-and-people-1", "name": "Bots & People", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "clarius", "name": "Clarius", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "dpa", "name": "dpa Deutsche Presse", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Düsseldorf' OR 'Stuttgart') AND 'Remot"},
    {"ats": "personio", "token": "eraneos", "name": "Eraneos", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "fides-technology-gmbh", "name": "Fides ...", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('München' OR 'Bremen') AND 'Re"},
    {"ats": "personio", "token": "freshcells-gmbh", "name": "freshcells systems engineering ...", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' AND ('Düsseldorf' OR 'Stuttgart') AND 'Remo"},
    {"ats": "personio", "token": "justaddai", "name": "JAAI Group", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('München' OR 'Bremen') AND 'Remote'"},
    {"ats": "personio", "token": "rebike-mobility", "name": "Junior Data Engineer (m/f/d) -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('München' OR 'Bremen') AND 'Remote'"},
    {"ats": "personio", "token": "jaai", "name": "JUST ADD AI GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('München' OR 'Bremen') AND 'Re"},
    {"ats": "personio", "token": "krisenchat", "name": "krisenchat", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "mamahealth", "name": "mama health", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "mtr-rechtsanwaltsgesellschaft-mbh", "name": "Mtr Rechtsanwaltsgesellschaft Mbh", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Frankfurt' OR 'Köln') AND 'Remote'"},
    {"ats": "personio", "token": "mway", "name": "MWAY DIGITAL GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    {"ats": "personio", "token": "myty", "name": "Myty", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Düsseldorf' OR 'Stuttgart') AND 'Remot"},
    {"ats": "personio", "token": "neoshare", "name": "neoshare", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    {"ats": "personio", "token": "omnora", "name": "Omnora", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Frankfurt' OR 'Köln') AND 'Remote'"},
    {"ats": "personio", "token": "pmone", "name": "pmOne", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('München' OR 'Bremen') AND 'Remote'"},
    {"ats": "personio", "token": "q-ant-gmbh", "name": "Q Ant Gmbh", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    {"ats": "personio", "token": "rindus", "name": "rindus GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    {"ats": "personio", "token": "scoutastic", "name": "SCOUTASTIC GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('München' OR 'Bremen') AND 'Remote'"},
    {"ats": "personio", "token": "seroton", "name": "Seroton GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('München' OR 'Bremen') AND 'Re"},
    {"ats": "personio", "token": "holidaycheck", "name": "Software Engineer – User Generated Content (all genders) -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('München' OR 'Bremen') AND 'Re"},
    {"ats": "personio", "token": "sunhat", "name": "Sunhat GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "synaos-gmbh", "name": "SYNAOS GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Hannover' OR 'Leipzig') AND '"},
    {"ats": "personio", "token": "syzygy", "name": "SYZYGY", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('Frankfurt' OR 'Köln') AND 'Remote'"},
    {"ats": "personio", "token": "stackfuel-gmbh", "name": "Tutor / Dozent (Fokus: KI) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "workidentity", "name": "Workidentity", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Hannover' OR 'Leipzig') AND 'Remote'"},
    {"ats": "personio", "token": "zdf-sparks", "name": "ZDF Sparks GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "adorsys", "name": "adorsys GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Nürnberg' OR 'Dresden') AND '"},
    {"ats": "personio", "token": "es-tecgroup", "name": "Es Tecgroup", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Nürnberg' OR 'Dresden') AND '"},
    {"ats": "personio", "token": "findiq-gmbh", "name": "FINDIQ GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    {"ats": "personio", "token": "homaris", "name": "Homaris", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Nürnberg' OR 'Dresden') AND '"},
    {"ats": "personio", "token": "dymatrix", "name": "Software Engineer – Full Stack (.NET/React) (all genders) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    {"ats": "personio", "token": "swan-gmbh", "name": "Swan Gmbh", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Nürnberg' OR 'Dresden') AND '"},
    {"ats": "personio", "token": "admi", "name": "admi Kommunal GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    {"ats": "personio", "token": "digital-loop", "name": "Computer Lingvist (Freelancer) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('München' OR 'Bremen') AND 'Remote'"},
    {"ats": "personio", "token": "finnofleet", "name": "Finnofleet", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI' AND ('Hamburg' OR 'Berlin') AND 'Remote'"},
    {"ats": "personio", "token": "octonomy-ai", "name": "Staff Machine Learning Engineer (m/f/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' AND ('Frankfurt' OR 'Köln') AND 'Remote'"},
    {"ats": "personio", "token": "silicon-austria-labs", "name": "Silicon Austria Labs", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Mannheim' OR 'Heidelberg') AN"},
    {"ats": "personio", "token": "accumin", "name": "Accumin", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Hannover' OR 'Leipzig') AND '"},
    {"ats": "personio", "token": "dishdigital", "name": "Dishdigital", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' AND ('Düsseldorf' OR 'Stuttgart') AND 'Remot"},
    {"ats": "personio", "token": "franka-robotics", "name": "FRANKA ROBOTICS", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('München' OR 'Bremen') AND 'Re"},
    {"ats": "personio", "token": "getsafe", "name": "Getsafe", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Mannheim' OR 'Heidelberg') AN"},
    {"ats": "personio", "token": "dachs-it", "name": "Solution Architect (Managed Services) (m/w/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' AND ('Düsseldorf' OR 'Stuttgart') A"},
    # ===== ARBEITNOW (cross-company aggregator — single pseudo-entry) =====
    {"ats": "arbeitnow", "token": "_aggregator", "name": "arbeitnow.com",
     "tier": "platform", "verified": True,
     "notes": "EU tech job aggregator, ~150-300 fresh jobs/day, no auth"},

    # ===== RECRUITEE seeds (popular for German/EU SMB) =====
    # Discovery will append more; these are well-known DE/EU tenants.

    # ===== SMARTRECRUITERS seeds (Bosch, Henkel etc.) =====
    {"ats": "smartrecruiters", "token": "BoschGroup", "name": "Bosch Group",
     "tier": "enterprise", "verified": True,
     "notes": "Stuttgart-based; ~4000+ jobs"},

    # ===== WORKDAY seeds (token format: tenant:server:site) =====
    # Discovery is harder for Workday because each tenant uses a different
    # server (wd1/wd3/wd5) and site name. Add manually as found.

    {"ats": "personio", "token": "accantec-group", "name": "AI Engineer (m/w/d) -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' 'Hamburg' (remote OR 'work from home')"},
    {"ats": "personio", "token": "apo", "name": "Apo", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' 'Deutschland' (remote OR 'work from home')"},
    {"ats": "personio", "token": "chargecloud-gmbh", "name": "Chargecloud Gmbh", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Deutschland' (remote OR 'work from home'"},
    {"ats": "personio", "token": "data4life", "name": "Data4Life", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "digetiers-gmbh", "name": "Digetiers GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "mpire", "name": "Initiativbewerbung (m/w/d) – RIVA-Gruppe |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Frankfurt' (remote OR 'work from home')"},
    {"ats": "personio", "token": "johner-institut-gmbh", "name": "Johner Institut Gmbh", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Frankfurt' (remote OR 'work from home')"},
    {"ats": "personio", "token": "legalhero", "name": "Legalhero", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "lautsprecherteufel", "name": "Master Data Manager (m/w/d) im Supply Chain Management |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "meteocontrol", "name": "meteocontrol GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "thermondo", "name": "Mobile Engineer (f/m/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "munerio", "name": "Munerio", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "xayn", "name": "Noxtua", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "silbury", "name": "Offene Stellen -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' 'Deutschland' (remote OR 'work from home')"},
    {"ats": "personio", "token": "element-personalberatung", "name": "Personalberater:in (m/w/d) -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Frankfurt' (remote OR 'work from home')"},
    {"ats": "personio", "token": "prematch-sports-gmbh", "name": "PREMATCH Sports GmbH", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "it-haus-gmbh", "name": "Sales Specialist Microsoft 365 (m/w/d) -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Frankfurt' (remote OR 'work from home')"},
    {"ats": "personio", "token": "dia", "name": "Salesforce Developer (m/w/d) | 100% Remote |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "sassyclassy", "name": "Sassyclassy", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' 'München' (remote OR 'work from home')"},
    {"ats": "personio", "token": "cito-transport-technologies", "name": "Senior AI & Software Engineer (m/w/d) – remote |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "taod", "name": "Taod", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Engineer' 'Stuttgart'"},
    {"ats": "personio", "token": "tandem", "name": "Technical Product Manager |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "zollsoft", "name": "Zollsoft", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "ideals", "name": "Account Executive - Frankfurt (m/w/d) @ Ideals -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Frankfurt' (remote OR 'work from h"},
    {"ats": "ashby", "token": "ellamind", "name": "AI Engineer (all genders) @ ellamind -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "kuro", "name": "AI Engineer @ Kuro Technology -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "airwallex", "name": "Airwallex -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Developer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "taktile", "name": "Back-End Engineer - Team Agents @ Taktile -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "cradlebio", "name": "Cradle -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Zürich' (remote OR 'work from home"},
    {"ats": "ashby", "token": "qdrant.tech", "name": "Developer Relations Engineer - EMEA @ Qdrant -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Developer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "elevenlabs", "name": "ElevenLabs -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Zürich' (remote OR 'work from home"},
    {"ats": "ashby", "token": "featherlessai", "name": "Founding Account Executive (AI Cloud) @ Featherless AI -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Developer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "g2i", "name": "G2i Inc. -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Engineer' 'Stuttgart'"},
    {"ats": "ashby", "token": "hilberts", "name": "Hilbert's AI -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "smallpdf", "name": "Information Security & Compliance Officer @ smallpdf -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Zürich' (remote OR 'work from home"},
    {"ats": "ashby", "token": "publiccloudgroup", "name": "IT Systemadministrator (m/w/d) - Internal Infrastructure -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'GenAI Engineer' 'Hamburg' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "whatnot", "name": "LLM Platform Engineer @ Whatnot -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'LLM Engineer' 'Deutschland' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "omnilex", "name": "Omnilex -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Engineer' 'Zürich' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "openai", "name": "OpenAI -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Zürich' (remote OR 'work from home"},
    {"ats": "ashby", "token": "perplexity", "name": "Perplexity -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Berlin' (remote OR 'work from home"},
    {"ats": "ashby", "token": "pplwise", "name": "pplwise -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Berlin' (remote OR 'work from home"},
    {"ats": "ashby", "token": "synthesia", "name": "Product Designer (Staff/Principal-level) @ Synthesia -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Zürich' (remote OR 'work from home"},
    {"ats": "ashby", "token": "Kombo", "name": "Product Engineer (Full Stack) @ Kombo -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "upvest", "name": "Security Engineering Lead (m/f/d) @ Upvest -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "ledger", "name": "Senior Frontend Engineer @ Ledger -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Zürich' (remote OR 'work from home"},
    {"ats": "ashby", "token": "blp-digital", "name": "Software Engineer ERP Integrations @ BLP Digital AG -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Software Engineer' 'Zürich' (remote OR 'work from home"},
    {"ats": "ashby", "token": "leapsome", "name": "Staff Product Engineer (d/f/m) @ Leapsome -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "Superhuman%20Platform%20Inc", "name": "Superhuman - Software Engineer, Full-Stack -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'LLM Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "ashby", "token": "xpreso", "name": "Xpreso -", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.ashbyhq.com 'AI Engineer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "coeo-group-gmbh", "name": "AI Developer (m/w/d) - Fokus MLOps |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Developer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "biteam", "name": "AI Developer (m/w/d)​ |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Developer' 'Berlin' (remote OR 'work from home')"},
    {"ats": "personio", "token": "pink-university-gmbh", "name": "AI Solutions Developer mit Tech Focus (m/w/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Hamburg' (remote OR 'work from home')"},
    {"ats": "personio", "token": "autarcenergy", "name": "autarc", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' 'Berlin' (remote OR 'work from home"},
    {"ats": "personio", "token": "azeti", "name": "Azeti", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' 'Berlin' (remote OR 'work from home"},
    {"ats": "personio", "token": "baramundi-software-ag", "name": "baramundi software", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'LLM Engineer' 'Deutschland' (remote OR 'work from home')"},
    {"ats": "personio", "token": "gen-up", "name": "Gen Up", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Developer' 'Frankfurt' (remote OR 'work from home')"},
    {"ats": "personio", "token": "invensity-group", "name": "INVENSITY Stellenportal", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Developer' 'Düsseldorf' (remote OR 'work from home')"},
    {"ats": "personio", "token": "jeanlen", "name": "Jeanlen", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Köln' (remote OR 'work from home')"},
    {"ats": "personio", "token": "maibornwolff", "name": "Lead AI Engineer (w/m/d) IT-Consulting |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' 'Hamburg' (remote OR 'work from hom"},
    {"ats": "personio", "token": "satisfyer", "name": "Satisfyer", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Developer' 'Düsseldorf' (remote OR 'work from home')"},
    {"ats": "personio", "token": "towa", "name": "Senior MarTech & Customer Data Engineer (m/w/d), Bregenz |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Hamburg' (remote OR 'work from home')"},
    {"ats": "personio", "token": "visable", "name": "Senior QA Engineer (Automation) (m/w/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' 'Hamburg' (remote OR 'work from hom"},
    {"ats": "personio", "token": "spaceteams", "name": "Senior Software Engineer (m/w/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Hamburg' (remote OR 'work from home')"},
    {"ats": "personio", "token": "trusteq-gmbh", "name": "TRUSTEQ", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' 'Köln' (remote OR 'work from home')"},
    {"ats": "personio", "token": "vamo", "name": "Vamo", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'AI Software Engineer' 'Köln' (remote OR 'work from home')"},
    {"ats": "personio", "token": "nexum-ag", "name": "Werkstudent Consulting (m/w/d) |", "tier": "scaleup", "verified": True, "notes": "live-discovered: site:jobs.personio.de 'GenAI Engineer' 'Hamburg' (remote OR 'work from home')"},
    # <<< new entries are appended above this line >>>
]


def _dedup(entries: list[dict]) -> list[dict]:
    """Deduplicate by (ats, token) — last writer wins on exact key collision."""
    seen: dict[tuple, int] = {}
    result: list[dict] = []
    for entry in entries:
        key = (entry["ats"], entry["token"].lower())
        if key in seen:
            result[seen[key]] = entry
        else:
            seen[key] = len(result)
            result.append(entry)
    return result


COMPANIES: list[dict] = _dedup(_RAW)


def companies_by_ats() -> dict:
    """Group COMPANIES by ATS for diagnostics."""
    out: dict = {}
    for c in COMPANIES:
        out.setdefault(c["ats"], []).append(c)
    return out
